### ISSUE TITLE
/nu lp 相关bug

### ISSUE THREAD

**Issue by Misaka-0x447f** [NyaaCat/NyaaUtils#61]
原文地址：[https://bbs.craft.moe/d/843-inf-nu-lp](https://bbs.craft.moe/d/843-inf-nu-lp)

## /nu lp可能的状态
1. 关闭
2. 开启 - ignorevanilla/ig
3. 开启 - rejectvanilla/re
4. 开启 - acceptvanilla/ac
5. 开启 - includevanilla
6. 开启
其中，状态1与状态2相同，但提示文字不同。状态4与状态5文字提示相同，且均没有效果。

## 状态5
~~状态5是一个比较特殊的状态。根据卷的说法，状态5等于状态4，但实际测试表明，切换到状态5时，服务器提示与状态4相同，但实际状态与切换前一致。换句话说切换前是状态1，切换后实际上也是状态1。
而原版手册上有状态5，却没有状态4。~~
~~也就是说，状态5是一个在手册中存在，但实际不存在的状态。这应该是一个状态重命名过程中留下的bug，等下写完之后报给卷等修复。~~
并不是这样的，之后的测试表明状态5等于状态4，二者均有文字提示而没有实际进行切换。

## 所有状态的详细解释
1. 关闭 - 完全关闭这个功能。不会自动拾取任何物品。
  如何进入此状态：不断输入```/nu lp```，直到你看见"掉落物保护已关闭"为止。
2. 开启 - ig - 不会自动拾取任何原版物品与经验球。
  如何进入状态：输入```/nu lp ig```或```/nu lp ignorevanilla```
3. 开启 - re - 不会自动拾取任何原版物品与经验球，除非按下shift。
  如何进入：输入```/nu lp re```或...
4. 开启 - ac - 自动拾取任何物品。
  如何：```/nu lp ac```或...
5. 开启 - in
  目前的黑盒测试认为该状态等于状态4。
  如何：```/nu lp includevanilla```。没有或。
6. 开启 - 自动拾取任何物品。
  如何进入此状态：不断输入```/nu lp```，直到你看见"掉落物保护已开启"为止。
  
## 上文bug汇总 + 其他杂项bug报告
> 本文中提到的"相同"均指黑盒测试认为其表现一致。

- [ ] 状态1与状态2效果相同，但提示文字不同。请对其进行合并。
- [ ] 状态5与状态4相同，且都没有效果。切换到此状态不会改变之前的状态。比如说，选择1再选择5，服务器显示已切换到5，但实际上的状态还是1。
- [ ] 状态5不能通过输入/nu lp in进入。
- [ ] 状态4、5、6在设计时作用相同，请对其进行合并。
- [ ] 状态1的提示信息有冲突。第一行是"掉落物保护已关闭"，第二行是"掉落物由最后击杀的玩家获得"，这两句话的含义相互矛盾。
- [ ] 如果输入/nu lp <任意字符串>，将会仅显示掉落物由最后击杀的玩家获得这一行文字。正确的显示应该是该命令的帮助文本。

## TODO
由于目前没有人帮我做多人测试，暂时还是不能确定"掉落物由最后击杀的玩家获得"这句话是否隐含着这个含义："掉落物不能由最后击杀的玩家以外的人获得"。
